from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path

PLUGIN_ROOT = Path(__file__).resolve().parents[3]
BOOPING_BIN = PLUGIN_ROOT / "bin" / "booping"
VAULT_FULL = Path(__file__).resolve().parents[1] / "__fixtures__" / "vault-full"


def _setup_fake_vault(tmp_path: Path) -> tuple[Path, Path, dict[str, str]]:
    """Set up a fake home + repo dir for subprocess tests.

    Returns (repo_dir, vault_dir, env) where:
    - repo_dir has a .booping marker with project_name: vault-full
    - vault_dir is fake_home/Claude/vault-full (copy of VAULT_FULL)
    - env has HOME pointing at fake_home
    """
    fake_home = tmp_path / "home"
    vault = fake_home / "Claude" / "vault-full"
    shutil.copytree(VAULT_FULL, vault)

    repo = tmp_path / "repo"
    repo.mkdir()
    (repo / ".booping").write_text("project_name: vault-full\n")

    env = dict(os.environ)
    env["HOME"] = str(fake_home)

    return repo, vault, env


def test_output_flag_writes_file_with_plan_rows(tmp_path: Path) -> None:
    """--output PATH writes sprints.md with header comment and plan data rows."""
    repo, _vault, env = _setup_fake_vault(tmp_path)
    output_file = tmp_path / "sprints.md"

    result = subprocess.run(
        [str(BOOPING_BIN), "render-sprints", "--output", str(output_file)],
        cwd=repo,
        env=env,
        capture_output=True,
        text=True,
        check=True,
    )

    assert output_file.exists()
    content = output_file.read_text()
    assert "<!-- Snapshot generated by booping render-sprints" in content
    assert "| status | sp | title |" in content
    assert "Add search feature" in content
    assert "wrote 2 plans to" in result.stderr


def test_output_dash_writes_to_stdout(tmp_path: Path) -> None:
    """--output - writes rendered content to stdout and does not create sprints.md."""
    repo, vault, env = _setup_fake_vault(tmp_path)

    sprints_file = vault / "sprints.md"
    if sprints_file.exists():
        sprints_file.unlink()

    result = subprocess.run(
        [str(BOOPING_BIN), "render-sprints", "--output", "-"],
        cwd=repo,
        env=env,
        capture_output=True,
        text=True,
        check=True,
    )

    assert "<!-- Snapshot generated by booping render-sprints" in result.stdout
    assert "Fix login timeout" in result.stdout
    assert not sprints_file.exists()


def test_output_flag_creates_parent_directories(tmp_path: Path) -> None:
    """--output PATH creates missing parent directories."""
    repo, _vault, env = _setup_fake_vault(tmp_path)
    nested_output = tmp_path / "custom" / "nested" / "sprints.md"
    assert not nested_output.parent.exists()

    subprocess.run(
        [str(BOOPING_BIN), "render-sprints", "--output", str(nested_output)],
        cwd=repo,
        env=env,
        capture_output=True,
        text=True,
        check=True,
    )

    assert nested_output.exists()
    assert "<!-- Snapshot generated by booping render-sprints" in nested_output.read_text()


def test_no_project_exits_with_code_2(tmp_path: Path) -> None:
    """Running outside any project (no .booping walk-up) exits with code 2."""
    result = subprocess.run(
        [str(BOOPING_BIN), "render-sprints"],
        cwd=tmp_path,
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode == 2
    assert result.stderr.strip() != ""
    assert "project" in result.stderr.lower()
