from __future__ import annotations

import argparse
import os
import subprocess
from pathlib import Path
from typing import Any

import pytest

from booping.commands import transition as transition_cmd
from booping.context.project import Project

PLUGIN_ROOT = Path(__file__).resolve().parents[3]
BOOPING_BIN = PLUGIN_ROOT / "bin" / "booping"


# ---------------------------------------------------------------------------
# Subprocess fixture: a real git vault + a real git repo dir.
#
# Project.directory resolves to HOME/Claude/<name>, and vault-commit needs that
# directory to be a git repo; @head interpolation needs the repo dir (the one
# carrying .booping) to be a git repo too.
# ---------------------------------------------------------------------------

def _git(cwd: Path, args: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", *args],
        cwd=str(cwd),
        capture_output=True,
        text=True,
        check=True,
    )


def _init_git(directory: Path) -> None:
    _git(directory, ["init"])
    _git(directory, ["config", "user.email", "test@example.com"])
    _git(directory, ["config", "user.name", "Test"])


def _setup(tmp_path: Path) -> tuple[Path, Path, Path, dict[str, str]]:
    """Build a fake home + vault git repo + project repo dir.

    Returns (repo_dir, vault_dir, plan_path, env).
    - repo_dir carries .booping (project_name: tproj) and is a git repo (for @head).
    - vault_dir is fake_home/Claude/tproj, a git repo (for vault-commit), with an
      in-spec plan + sprints.md committed.
    - env has HOME pointing at the fake home.
    """
    fake_home = tmp_path / "home"
    vault = fake_home / "Claude" / "tproj"
    (vault / "plans").mkdir(parents=True)

    _init_git(vault)
    plan = vault / "plans" / "20260101-my-feature.md"
    plan.write_text(
        "---\nstatus: in-spec\ntitle: My feature\ntype: feature\nsp: 3\n"
        "planned: null\ncommit: null\n---\n\n# Plan body\n"
    )
    (vault / "sprints.md").write_text(
        "# Sprints\n\n| status | sp | title |\n| --- | --- | --- |\n"
    )
    _git(vault, ["add", "plans/20260101-my-feature.md", "sprints.md"])
    _git(vault, ["commit", "-m", "initial"])

    repo = tmp_path / "repo"
    repo.mkdir()
    (repo / ".booping").write_text("project_name: tproj\n")
    _init_git(repo)
    (repo / "README.md").write_text("# repo\n")
    _git(repo, ["add", "README.md", ".booping"])
    _git(repo, ["commit", "-m", "repo initial"])

    env = dict(os.environ)
    env["HOME"] = str(fake_home)

    return repo, vault, plan, env


def _run_transition(
    repo: Path, env: dict[str, str], *cli_args: str
) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [str(BOOPING_BIN), "transition", *cli_args],
        cwd=repo,
        env=env,
        capture_output=True,
        text=True,
        check=False,
    )


# ---------------------------------------------------------------------------
# 1. Happy path
# ---------------------------------------------------------------------------

class TestHappyPath:
    def test_valid_edge_runs_all_hooks_in_order(self, tmp_path: Path) -> None:
        repo, vault, plan, env = _setup(tmp_path)

        result = _run_transition(
            repo, env, "awaiting-plan-review", str(plan)
        )
        assert result.returncode == 0, result.stderr

        # Frontmatter updated: status + planned + commit.
        from booping.context._yaml import parse_frontmatter_only

        fm = parse_frontmatter_only(plan)
        assert fm["status"] == "awaiting-plan-review"
        assert fm["planned"] not in (None, "null", "")
        assert fm["commit"] not in (None, "null", "")

        # sprints.md regenerated (booping snapshot header replaces the stub).
        assert "Snapshot generated by booping render-sprints" in (
            vault / "sprints.md"
        ).read_text()

        # Exactly one new vault commit, naming the target status + plan stem.
        log = _git(vault, ["log", "--oneline"]).stdout.strip().splitlines()
        assert len(log) == 2  # initial + the transition commit
        assert "awaiting-plan-review: 20260101-my-feature" in log[0]


# ---------------------------------------------------------------------------
# 1a. Transition report on stdout
# ---------------------------------------------------------------------------

class TestReport:
    def test_report_lines_match_contract(self, tmp_path: Path) -> None:
        repo, vault, plan, env = _setup(tmp_path)

        result = _run_transition(repo, env, "awaiting-plan-review", str(plan))
        assert result.returncode == 0, result.stderr

        lines = result.stdout.strip().splitlines()
        assert lines[0] == "in-spec → awaiting-plan-review"

        # status set, then the edge's planned/commit stamps.
        assert lines[1] == "frontmatter: status=awaiting-plan-review"
        # `planned=@now` resolves to "YYYYmmdd HH:MM" — quoted because it has a space.
        assert lines[2].startswith('frontmatter: planned="')
        assert lines[2].endswith('"')
        head = _git(repo, ["rev-parse", "HEAD"]).stdout.strip()
        assert lines[3] == f"frontmatter: commit={head}"

        assert lines[4] == f"render-sprints: 1 plans → {vault / 'sprints.md'}"

        short = _git(vault, ["rev-parse", "--short", "HEAD"]).stdout.strip()
        assert lines[5] == f"vault-commit: {short}"
        assert len(lines) == 6

    def test_stdout_carries_only_the_report(self, tmp_path: Path) -> None:
        repo, _vault, plan, env = _setup(tmp_path)

        result = _run_transition(repo, env, "awaiting-plan-review", str(plan))
        assert result.returncode == 0, result.stderr

        for line in result.stdout.strip().splitlines()[1:]:
            assert line.split(":")[0] in (
                "frontmatter",
                "render-sprints",
                "vault-commit",
            )

    def test_report_with_also(self, tmp_path: Path) -> None:
        repo, vault, plan, env = _setup(tmp_path)
        artifact = vault / "retro" / "20260101-my-feature.md"
        artifact.parent.mkdir(parents=True)
        artifact.write_text("# Retrospective\n")

        result = _run_transition(
            repo, env, "awaiting-plan-review", str(plan), "--also", str(artifact)
        )
        assert result.returncode == 0, result.stderr

        short = _git(vault, ["rev-parse", "--short", "HEAD"]).stdout.strip()
        lines = result.stdout.strip().splitlines()
        assert lines[0] == "in-spec → awaiting-plan-review"
        assert lines[-1] == f"vault-commit: {short}"

    def test_nothing_to_commit_reported(self, tmp_path: Path) -> None:
        repo, _vault, plan, env = _setup(tmp_path)

        first = _run_transition(repo, env, "awaiting-plan-review", str(plan))
        assert first.returncode == 0, first.stderr

        # Nothing changed since the first move: the vault-commit hook has no
        # diff to record.
        second = _run_transition(repo, env, "awaiting-plan-review", str(plan))
        assert second.returncode == 0, second.stderr

        lines = second.stdout.strip().splitlines()
        assert lines[0] == "awaiting-plan-review → awaiting-plan-review (idempotent)"
        assert lines[-1] == "vault-commit: nothing to commit"


# ---------------------------------------------------------------------------
# 1b. --also passthrough
# ---------------------------------------------------------------------------

class TestAlsoPassthrough:
    def test_also_artifact_committed_alongside_plan(self, tmp_path: Path) -> None:
        repo, vault, plan, env = _setup(tmp_path)

        artifact = vault / "retro" / "20260101-my-feature.md"
        artifact.parent.mkdir(parents=True)
        artifact.write_text("# Retrospective\n")

        result = _run_transition(
            repo, env, "awaiting-plan-review", str(plan), "--also", str(artifact)
        )
        assert result.returncode == 0, result.stderr

        # Exactly one new commit, and it carries the artifact + plan + sprints.md.
        log = _git(vault, ["log", "--oneline"]).stdout.strip().splitlines()
        assert len(log) == 2  # initial + the transition commit

        files = _git(
            vault, ["show", "--name-only", "--pretty=format:", "HEAD"]
        ).stdout.strip().splitlines()
        files = [f for f in files if f]
        assert "retro/20260101-my-feature.md" in files
        assert "plans/20260101-my-feature.md" in files
        assert "sprints.md" in files

        # The artifact is committed (not lingering as untracked / unstaged).
        porcelain = _git(vault, ["status", "--porcelain"]).stdout.strip()
        assert "retro/20260101-my-feature.md" not in porcelain

    def test_without_also_does_not_commit_extra_artifacts(
        self, tmp_path: Path
    ) -> None:
        repo, vault, plan, env = _setup(tmp_path)

        # An unrelated artifact present in the vault but not passed via --also.
        stray = vault / "retro" / "20260101-my-feature.md"
        stray.parent.mkdir(parents=True)
        stray.write_text("# Retrospective\n")

        result = _run_transition(repo, env, "awaiting-plan-review", str(plan))
        assert result.returncode == 0, result.stderr

        # The transition commit stages only plan + sprints.md; the stray file is
        # left untracked.
        files = _git(
            vault, ["show", "--name-only", "--pretty=format:", "HEAD"]
        ).stdout.strip().splitlines()
        files = [f for f in files if f]
        assert "retro/20260101-my-feature.md" not in files
        assert "plans/20260101-my-feature.md" in files
        assert "sprints.md" in files

        porcelain = _git(
            vault, ["status", "--porcelain", "--untracked-files=all"]
        ).stdout
        assert "?? retro/20260101-my-feature.md" in porcelain


# ---------------------------------------------------------------------------
# 2. Invalid target
# ---------------------------------------------------------------------------

class TestInvalidTarget:
    def test_bogus_status_exits_1_and_lists_allowed(self, tmp_path: Path) -> None:
        repo, _vault, plan, env = _setup(tmp_path)

        result = _run_transition(repo, env, "totally-bogus", str(plan))

        assert result.returncode == 1
        # in-spec's allowed targets surface in stderr.
        assert "awaiting-plan-review" in result.stderr
        assert "totally-bogus" in result.stderr


# ---------------------------------------------------------------------------
# In-process fixtures for hook-injection scenarios.
#
# The dispatcher loads config via config_mod.load(plugin_root, []) and does NOT
# honour vault config overrides, so a synthetic config must be injected by
# monkeypatching the loader the dispatcher imports.
# ---------------------------------------------------------------------------

def _stub_project(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    """Make Project.load_cwd return a project whose vault is a writable tmp dir."""
    vault = tmp_path / "vault"
    (vault / "plans").mkdir(parents=True)

    def _fake_load_cwd(
        cls: type[Project], start: Path | None = None, home_dir: str = "~/Claude"
    ) -> Project:
        return Project(
            name="tproj",
            directory=vault,
            repo_directory=tmp_path,
            git_commit=None,
        )

    monkeypatch.setattr(Project, "load_cwd", classmethod(_fake_load_cwd))
    return vault


def _make_plan(vault: Path, status: str) -> Path:
    plan = vault / "plans" / "20260101-my-feature.md"
    plan.write_text(f"---\nstatus: {status}\ntitle: My feature\n---\n\n# Body\n")
    return plan


def _inject_config(
    monkeypatch: pytest.MonkeyPatch, hooks_for_edge: list[str]
) -> None:
    """Patch the config loader the dispatcher uses to return a one-edge config
    whose in-spec → awaiting-plan-review transition carries hooks_for_edge."""
    from booping.context import config as config_mod

    cfg: dict[str, Any] = {
        "plan": {
            "superstates": {
                "planning": {
                    "substates": ["in-spec", "awaiting-plan-review"],
                    "on_entry": [],
                }
            },
            "statuses": {
                "in-spec": {
                    "transitions": [
                        {
                            "to": "awaiting-plan-review",
                            "skill": "groom",
                            "hooks": hooks_for_edge,
                        }
                    ]
                },
                "awaiting-plan-review": {"transitions": []},
            },
            "hooks": {"post": []},
        }
    }

    def _fake_load(root: Path, overrides: list[Path]) -> dict[str, Any]:
        return cfg

    monkeypatch.setattr(config_mod, "load", _fake_load)


# ---------------------------------------------------------------------------
# 3. Unknown hook name
# ---------------------------------------------------------------------------

class TestUnknownHook:
    def test_unknown_hook_exits_2(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
        capsys: pytest.CaptureFixture[str],
    ) -> None:
        vault = _stub_project(tmp_path, monkeypatch)
        plan = _make_plan(vault, "in-spec")
        _inject_config(monkeypatch, ["bogus-hook some=thing"])

        args = argparse.Namespace(
            to_status="awaiting-plan-review", plan=plan, also=None
        )
        with pytest.raises(SystemExit) as excinfo:
            transition_cmd._run(args)  # type: ignore[reportPrivateUsage]

        assert excinfo.value.code == 2
        assert "bogus-hook" in capsys.readouterr().err


# ---------------------------------------------------------------------------
# 4. Hook failure mid-list
# ---------------------------------------------------------------------------

class TestHookFailureMidList:
    def test_failing_hook_aborts_with_exit_2(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
        capsys: pytest.CaptureFixture[str],
    ) -> None:
        vault = _stub_project(tmp_path, monkeypatch)
        plan = _make_plan(vault, "in-spec")
        # First hook ok; second hook is malformed (no '=') → frontmatter-update
        # parse exits 1, which the dispatcher re-raises as a named failure.
        _inject_config(
            monkeypatch,
            [
                "frontmatter-update status=awaiting-plan-review",
                "frontmatter-update malformed-no-equals",
            ],
        )

        args = argparse.Namespace(
            to_status="awaiting-plan-review", plan=plan, also=None
        )
        with pytest.raises(SystemExit) as excinfo:
            transition_cmd._run(args)  # type: ignore[reportPrivateUsage]

        assert excinfo.value.code in (1, 2)
        err = capsys.readouterr().err
        assert "frontmatter-update" in err
        assert "failed" in err


# ---------------------------------------------------------------------------
# 5. Idempotent re-run
# ---------------------------------------------------------------------------

class TestIdempotentRerun:
    def test_status_already_target_runs_only_post_hooks(
        self, tmp_path: Path
    ) -> None:
        repo, vault, plan, env = _setup(tmp_path)

        # First move in-spec → awaiting-plan-review.
        first = _run_transition(repo, env, "awaiting-plan-review", str(plan))
        assert first.returncode == 0, first.stderr

        # Give vault-commit a real change to commit on the re-run by editing the
        # plan body (render-sprints regenerates a byte-identical snapshot, so the
        # plan edit is what proves vault-commit re-ran end-to-end).
        plan.write_text(plan.read_text() + "\nExtra note.\n")

        # Re-run targeting the same status: the missing in-spec edge must NOT
        # error; the dispatcher must take the idempotent path.
        second = _run_transition(repo, env, "awaiting-plan-review", str(plan))
        assert second.returncode == 0, second.stderr

        # Report: idempotent header + post-hook lines only (no frontmatter line).
        lines = second.stdout.strip().splitlines()
        assert lines[0] == "awaiting-plan-review → awaiting-plan-review (idempotent)"
        assert not any(line.startswith("frontmatter:") for line in lines)

        # render-sprints post-hook ran.
        assert f"render-sprints: 1 plans → {vault / 'sprints.md'}" in lines
        assert "Snapshot generated by booping render-sprints" in (
            vault / "sprints.md"
        ).read_text()

        # vault-commit post-hook ran, producing a third commit.
        log = _git(vault, ["log", "--oneline"]).stdout.strip().splitlines()
        assert len(log) == 3
        assert "awaiting-plan-review: 20260101-my-feature" in log[0]

        # Status stayed at the target (no spurious second frontmatter mutation).
        from booping.context._yaml import parse_frontmatter_only

        assert parse_frontmatter_only(plan)["status"] == "awaiting-plan-review"


# ---------------------------------------------------------------------------
# 6. Log line
# ---------------------------------------------------------------------------

class TestLogLine:
    def test_appends_transition_log_line(self, tmp_path: Path) -> None:
        repo, vault, plan, env = _setup(tmp_path)

        result = _run_transition(repo, env, "awaiting-plan-review", str(plan))
        assert result.returncode == 0, result.stderr

        log_path = vault / "_booping" / ".booping.log"
        assert log_path.is_file()
        lines = log_path.read_text().strip().splitlines()
        transition_lines = [line for line in lines if "[transition]" in line]
        assert len(transition_lines) == 1
        assert "in-spec→awaiting-plan-review" in transition_lines[0]
        assert str(plan) in transition_lines[0]


# ---------------------------------------------------------------------------
# 7. File-target frontmatter-update hooks
# ---------------------------------------------------------------------------

class TestFileTargetHook:
    def test_plan_transition_rejects_file_target(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
        capsys: pytest.CaptureFixture[str],
    ) -> None:
        vault = _stub_project(tmp_path, monkeypatch)
        plan = _make_plan(vault, "in-spec")
        _inject_config(monkeypatch, ["frontmatter-update brief.md reviewed=yes"])

        args = argparse.Namespace(
            to_status="awaiting-plan-review", plan=plan, also=None
        )
        with pytest.raises(SystemExit) as excinfo:
            transition_cmd._run(args)  # type: ignore[reportPrivateUsage]

        assert excinfo.value.code == 2
        assert (
            "file-target frontmatter-update is not supported in plan transitions"
            in capsys.readouterr().err
        )

    def test_no_target_dispatch_returns_none_target(self, tmp_path: Path) -> None:
        target = tmp_path / "plan.md"
        target.write_text("---\nstatus: in-spec\n---\n\n# Body\n")

        rel, resolved = transition_cmd.dispatch_frontmatter_update(
            "frontmatter-update status=ready-for-dev", target, None
        )

        assert rel is None
        assert resolved == {"status": "ready-for-dev"}

    def test_report_line_shapes(self) -> None:
        assert (
            transition_cmd.format_frontmatter_line({"status": "done"})
            == "frontmatter: status=done"
        )
        assert (
            transition_cmd.format_frontmatter_line(
                {"status": "done", "note": "two words"}, "_specs/brief.md"
            )
            == 'frontmatter _specs/brief.md: status=done note="two words"'
        )
