#!/usr/bin/env python3
"""Shared implementation for the plan-<status> hook scripts.

Invoked with the target lifecycle status as argv[1]. Environment (set by
`booping playbook-transition`): BOOPING_WORKDIR = {vault}/plans/{slug}.

Stamps `plan_status:` on the run's `index.md` (the run machine owns `status:`,
so the lifecycle mirror lives under its own key), re-renders the vault's
sprints.md from plan frontmatter, and commits both. Self-contained: the vault
carries no `.booping` marker, so nothing here shells back into `booping`.
"""

import os
import re
import subprocess
import sys
from pathlib import Path


def read_frontmatter(path: Path) -> dict[str, str]:
    text = path.read_text()
    m = re.match(r"\A---\n(.*?)\n---\n", text, re.DOTALL)
    if not m:
        return {}
    fm: dict[str, str] = {}
    for line in m.group(1).splitlines():
        if line.startswith((" ", "\t")) or ":" not in line:
            continue
        key, _, value = line.partition(":")
        value = value.split("  #")[0].strip().strip("\"'")
        fm[key.strip()] = "" if value in ("null", "~") else value
    return fm


def stamp_status(plan: Path, status: str) -> None:
    text = plan.read_text()
    if not text.startswith("---\n"):
        sys.exit(f"plan has no frontmatter: {plan}")
    head, sep, body = text.partition("\n---\n")
    if re.search(r"^plan_status:.*$", head, re.MULTILINE):
        head = re.sub(
            r"^plan_status:.*$", f"plan_status: {status}", head, count=1, flags=re.MULTILINE
        )
    else:
        head += f"\nplan_status: {status}"
    plan.write_text(head + sep + body)


def discover_plans(vault: Path) -> list[tuple[str, Path]]:
    """Mixed-shape discovery, mirroring `Plan.load_all`: `plans/{slug}/plan.md`
    (or `plans/{slug}/index.md`) directory plans shadow same-slug
    `plans/{slug}.md` file plans; `plan.md` wins when a directory has both."""
    plans_dir = vault / "plans"
    by_slug: dict[str, Path] = {}
    for name in ("plan.md", "index.md"):
        for p in plans_dir.glob(f"*/{name}"):
            by_slug.setdefault(p.parent.name, p)
    for p in plans_dir.glob("*.md"):
        by_slug.setdefault(p.stem, p)
    return sorted(by_slug.items())


def rel_link(vault: Path, path: Path) -> str:
    return str(path.relative_to(vault))


CELL = str.maketrans({"|": "\\|", "\n": " "})
COLUMNS = ("status", "sp", "title", "summary", "created", "planned", "completed", "retro")


def render_sprints(vault: Path) -> int:
    rows: list[tuple[str, list[str]]] = []
    for _, path in discover_plans(vault):
        fm = read_frontmatter(path)
        cells = [fm.get(key, "").translate(CELL) for key in COLUMNS]
        cells.append(rel_link(vault, path))
        rows.append((fm.get("created", ""), cells))

    with_date = sorted((r for r in rows if r[0]), key=lambda r: r[0], reverse=True)
    without_date = [r for r in rows if not r[0]]

    lines = [
        "<!-- Snapshot generated by booping render-sprints; regenerated by /chat on each orient. Do not hand-edit. -->",
        "| " + " | ".join((*COLUMNS, "path")) + " |",
        "| " + " | ".join(["---"] * (len(COLUMNS) + 1)) + " |",
    ]
    lines += ["| " + " | ".join(cells) + " |" for _, cells in with_date + without_date]
    (vault / "sprints.md").write_text("\n".join(lines) + "\n")
    return len(rows)


def main() -> None:
    status = sys.argv[1]
    workdir = Path(os.environ.get("BOOPING_WORKDIR", ".")).resolve()
    slug = workdir.name
    vault = workdir.parent.parent
    plan = workdir / "index.md"
    if not plan.is_file():
        sys.exit(f"plan not found: {plan}")

    stamp_status(plan, status)
    count = render_sprints(vault)
    print(f"plan-status: plans/{slug}/index.md → {status}; sprints.md: {count} plans")

    if (vault / ".git").exists():
        subprocess.run(
            ["git", "-C", str(vault), "add", f"plans/{slug}/index.md", "sprints.md"], check=True
        )
        result = subprocess.run(
            ["git", "-C", str(vault), "commit", "-q", "-m", f"groom: {slug} → {status}"],
        )
        print("vault-commit: ok" if result.returncode == 0 else "vault-commit: nothing to commit")


if __name__ == "__main__":
    main()
